blank_issues_enabled: true
contact_links:
  - name: Bug Report
    url: https://github.com/ruaan-deysel/ha-philips-airpurifier/issues/new?template=bug-report.yml
    about: Report a bug with a supported device
